# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dinesh
tagline:          'Dinesh Kumar Site'
description:      'Software engineer, Reads a lot, Sleeps a lot.ஏன்?எதற்கு?எப்படி? போன்ற பல கேள்விகளை தினமும் சந்தித்து பதில் தேடி கொண்டிருக்கும் ஒரு சராசரி மனிதன் நான்.'
url:              http://blog.dineshkumars.me
baseurl:          /

author:
  name:           'Dinesh Kumar S'
  url:            https://twitter.com/dinitwitt

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dinesh-kumar-11

stackoverflow
  link:
