# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dinesh Kumar Sarangapani
tagline:          'Dinesh Kumar Site'
description:      'Software engineer, Tech and Photography'
url:              http://blog.dineshkumars.me
baseurl:          /

author:
  name:           'Dinesh Kumar S'
  url:            https://twitter.com/dinitwitt

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dinesh-kumar-11

stackoverflow:
  link:           http://stackexchange.com/users/247492/dinesh-kumar

quora:
  link:           https://www.quora.com/profile/Dinesh-Kumar-71

flickr:
   photostream:   https://www.flickr.com/photos/diniphotos/

dinesh:
  home:         http://dineshkumars.me

sitemap:
  lastmod: 2016-04-07
  priority: 0.7
  changefreq: 'weekly'
  exclude: 'yes'

gems:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag